//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mezunbilgisistemi_proje_ödevi_
{
    using System;
    using System.Collections.Generic;
    
    public partial class isbilgileri
    {
        public int no { get; set; }
        public int Ogrno { get; set; }
        public Nullable<System.DateTime> IseGirisTarih { get; set; }
        public Nullable<System.DateTime> IstenAyrilisTar { get; set; }
        public string KamuOzel { get; set; }
        public string Sektor { get; set; }
        public string Unvan { get; set; }
        public string Pozisyon { get; set; }
    
        public virtual mezunlar mezunlar { get; set; }
    }
}
