//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mezunbilgisistemi_proje_ödevi_
{
    using System;
    using System.Collections.Generic;
    
    public partial class mezunlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mezunlar()
        {
            this.egitimbilgileri = new HashSet<egitimbilgileri>();
            this.isbilgileri = new HashSet<isbilgileri>();
        }
    
        public int Ogrno { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string MezuniyetTarih { get; set; }
        public string Ceptel { get; set; }
        public string Eposta { get; set; }
        public string EvTel { get; set; }
        public string EvUlke { get; set; }
        public string EvŞehir { get; set; }
        public string EvAdres { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<egitimbilgileri> egitimbilgileri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<isbilgileri> isbilgileri { get; set; }
    }
}
