//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mezunbilgisistemi_proje_ödevi_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mezunbilgisistemiEntities1 : DbContext
    {
        public mezunbilgisistemiEntities1()
            : base("name=mezunbilgisistemiEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<egitimbilgileri> egitimbilgileri { get; set; }
        public virtual DbSet<isbilgileri> isbilgileri { get; set; }
        public virtual DbSet<mezunlar> mezunlar { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblkullanici> tblkullanici { get; set; }
    }
}
