//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mezunbilgisistemi_proje_ödevi_
{
    using System;
    using System.Collections.Generic;
    
    public partial class egitimbilgileri
    {
        public int no { get; set; }
        public int Ogrno { get; set; }
        public string AkademikEgitim { get; set; }
        public string Baslangic { get; set; }
        public string Bitis { get; set; }
        public string Ulke { get; set; }
        public string Sehir { get; set; }
        public string Universite { get; set; }
    
        public virtual mezunlar mezunlar { get; set; }
    }
}
